### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by yokoboko** [myflashlab/facebook-ANE#43]
Hi,
I'm getting "Compilation failed while executing : ld64" error when i try to compile for ios with Air SDK 22 Beta(Version Date: May 25, 2016).
It works if u turn off "Hide Ane-Library-Symbols" but i need to be checked :(
Please help!

**Comment by myflashlab** [comment]
We had reported this issue to Adobe a few months ago and just today, Adobe
says that the problem is fixed on windows. Please check the discussion here
https://forums.adobe.com/message/8774270#8774270 and see if it's fixed?

Even if it isn't, as you might see in the forum posts, we had upgraded all
our ANEs few months ago to bypass this problem. So unless you are using
some other ANEs from other providers (whom might not be aware of this
problem at all) you will have no problem using ANEs from MyFlashLabs Team.

On Thursday, May 26, 2016, yokoboko <notifications@github.com> wrote:

> Hi,
> I'm getting "Compilation failed while executing : ld64" error when i try
> to compile for ios with Air SDK 22 Beta(Version Date: May 25, 2016).
> It works if u turn off "Hide Ane-Library-Symbols" but i need to be checked
> :(
> Please help!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/43>
>


-- 
Sent from iPhone

**Comment by yokoboko** [comment]
I created new test project and i still get this. Today i downloaded Adobe Air 22 Beta.

I still have problem with "Hide Ane-Library-Symbols".

![err](https://cloud.githubusercontent.com/assets/9528685/15577023/6da9a8c2-2363-11e6-9bc4-9d99db4d4fd4.png)

**Comment by myflashlab** [comment]
Adobe said they have fixed the problem. read the last comment here: https://forums.adobe.com/message/8774270#8774270 but if you still have problems with this feature, I think it would be best to update Adobe about the bug because there's nothing we can do about this.

P.S  When using our ANEs, you really don't have to tuen the -hideAneLibSymbols on at all. you can safely turn it off because none of our iOS ANEs would conflict with each other.
